1.3.4 API ref & Release notes updates
Nero-Hu/Whiteboard-Android-doc pull request #6
Opened 2023-04-17 09:17 UTC by Nero-Hu

2023-04-20 09:42 UTC, aderan approved these changes

2023-04-21 08:11 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +- `containerSizeRatio`：Float 类型。本地显示窗口中，内容的高宽比，默认为 `9:16`。
要加“类型”么？我看其他的都没加，不过加也无所谓

2023-04-21 08:31 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +- `true`：本地用户在当前互动白板实时房间为互动模式，即可对白板进行读写操作。
看到“即可”有点昏迷
前面两句写得很清楚了，`true`和`false`的描述要不简单点？
- `true`: 互动模式，即具有读写权限。
- `false`: 订阅模式，即具有只读权限。

2023-04-21 08:37 UTC, jinyuagora commented on Fastboard/CN-Release Notes.md
> +该版本新增在 `FastRoom` 类下新增 `setWritable` 方法，用于设置用户在房间中为具有读写权限的**互动模式**或只有只读权限的**订阅模式**。新增 `isWritable` 方法用于获取本地用户在当前互动白板实时房间是否为互动模式。
这里要不要写 setWritable [2/2] 啊，是不是加了个重载。

2023-04-21 08:45 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +白板颜色相关的资源
少个句号er

2023-04-21 08:52 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +- 如果不重写该方法，将默认调用 `getBackgroundColor`。
这个是不是不用 bullet

2023-04-21 08:56 UTC, jinyuagora commented on Fastboard/CN-Release Notes.md
> +该版本在 `FastRoom` 类下新增 `setResource` 方法，用于修改白板底色。你可以通过重写 `FastResource` 类中的方法来自定义白板底色。
这里是不是要补充一下：白板和白板**控件**的底色（我不确定这两个是怎么细分的，但是因为有两个成员方法

2023-04-21 09:04 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +- `darkMode`：boolean。白板控件底色是否为暗色模式：
话说默认是啥模式

2023-04-21 09:15 UTC, jinyuagora commented on Fastboard/CN-Release Notes.md
> +该版本在 `FastUiSettings` 类下新增 `setToolboxEdgeMargin` 方法，用于设置白板工具条的边距，即工具条边界和白板侧边之间的距离。
感觉直接写“用于设置工具条和白板侧边的边距”就好了，不要解释了（流汗黄豆

2023-04-21 09:18 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +### FastResult
为啥就 `FastResult` 不和方法写在一起，因为它是 interface 么

2023-04-21 09:24 UTC, jinyuagora commented on Fastboard/CN-Release Notes.md
> +该版本新增在 `FastRoom` 类下新增 `setWritable` 方法，用于设置用户在房间中为具有读写权限的**互动模式**或只有只读权限的**订阅模式**。新增 `isWritable` 方法用于获取本地用户在当前互动白板实时房间是否为互动模式。
“新增在 `FastRoom` 类下新增” --> “在 `FastRoom` 类下新增”

2023-04-21 09:41 UTC, jinyuagora commented on Fastboard/CN-Release Notes.md
> +该版本在 `FastRoomOptions` 类中新增 `userPayload` 属性，用于在白板房间中同步并展示用户光标的位置，且支持展示用户昵称和头像。
其实感觉你 iOS 这个肺切尔写得更清楚

> ，用于在白板房间中同步**其他**用户的光标位置并显示对应昵称和头像。**自该版本起，SDK 将默认显示用户光标。**

2023-04-21 09:42 UTC, jinyuagora commented on Fastboard/CN-API Reference.md
> +- `avatar`：String。用户光标上显示的用户头像，应传入头像对应的 URL 地址。
这个是 Optional 么

2023-04-23 02:15 UTC, Nero-Hu commented on Fastboard/CN-API Reference.md
> +- `containerSizeRatio`：Float 类型。本地显示窗口中，内容的高宽比，默认为 `9:16`。
跟其他的保持一致

2023-04-23 02:27 UTC, Nero-Hu commented on Fastboard/CN-API Reference.md
> +### FastResult
各种接口类中的方法都有可能用到它

2023-04-23 02:54 UTC, Nero-Hu commented on Fastboard/CN-API Reference.md
> +- `darkMode`：boolean。白板控件底色是否为暗色模式：
没有默认 重写回调的概念是用户需要指定在darkMode 分别为true / false 时候，返回什么颜色的值

2023-04-23 07:28 UTC, dengyaxi requested changes

2023-04-23 07:28 UTC, dengyaxi commented on Fastboard/CN-API Reference.md
> +### FastResult
可以考虑把 FastResult 作为二级标题么？放在 其他 下面有点怪

2023-04-23 07:28 UTC, dengyaxi commented on Fastboard/CN-Release Notes.md
> +
看到 iOS 有写“自该版本起，SDK 将默认显示用户光标”，Android 没有这一条改动咩（just 问问

2023-04-23 07:28 UTC, dengyaxi commented on Fastboard/CN-Release Notes.md
> +该版本在 `FastRoom` 类下新增 `setWritable [2/2]` 方法，用于设置用户在房间中为具有读写权限的**互动模式**或只有只读权限的**订阅模式**，支持通过回调函数异步处理调用结果。新增 `isWritable` 方法用于获取本地用户在当前互动白板实时房间是否为互动模式。
建议这里可以突出一下 2 和 1 的区别，也就是 2 支持异步处理调用结果。还可以补充下哪些常见场景会需要用 2 而不是1

2023-04-23 08:03 UTC, Nero-Hu commented on Fastboard/CN-Release Notes.md
> +
> 看到 iOS 有写“自该版本起，SDK 将默认显示用户光标”，Android 没有这一条改动咩（just 问问

没有，传了 userPayload 才会显示用户光标”

2023-04-23 08:03 UTC, Nero-Hu commented on Fastboard/CN-Release Notes.md
> +
> “同步其他用户的光标位置” 在 API 参考里似乎没有体现，是有什么隐藏的联系吗

传了 userPayload 后 SDK 会实现显示“同步其他用户的光标位置”

2023-04-23 08:07 UTC, Nero-Hu commented on Fastboard/CN-Release Notes.md
> +该版本在 `FastRoom` 类下新增 `setWritable [2/2]` 方法，用于设置用户在房间中为具有读写权限的**互动模式**或只有只读权限的**订阅模式**，支持通过回调函数异步处理调用结果。新增 `isWritable` 方法用于获取本地用户在当前互动白板实时房间是否为互动模式。
该版本在 `FastRoom` 类下新增 `setWritable [1/2]` 和 `setWritable [2/2]` 方法，用于设置用户在房间中为具有读写权限的**互动模式**或只有只读权限的**订阅模式**，其中，`setWritable [2/2]` 支持通过回调函数异步处理调用结果。

2023-04-23 08:13 UTC, Nero-Hu commented on Fastboard/CN-API Reference.md
> +设置白板控件底色。
你的理解很透彻

2023-04-24 06:09 UTC, Nero-Hu commented on Fastboard/CN-API Reference.md
> +- `containerSizeRatio`：Float。本地显示窗口中，内容的高宽比，默认为 `9:16`。
Float 是 Java 的系统类，是float的对象包装。传入时候传的是 0.56 （9 / 16）。

2023-04-24 07:09 UTC, dengyaxi commented on Fastboard/CN-API Reference.md
> +- `containerSizeRatio`：Float。本地显示窗口中，内容的高宽比，默认为 `9:16`。
学到了。那建议描述上可以再严谨些，类似 “默认值为 `0.56`，代表高宽比为 9:16“ 这样

2023-07-03 07:09 UTC, merged