2.16.59
Nero-Hu/Whiteboard-Android-doc pull request #7
Opened 2023-08-24 06:46 UTC by Nero-Hu

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/WhiteSdkConfiguration.java
> +     * 如果开启，在加载 url 资源时，SlideApp 会拦截图片并触发 {@link com.herewhite.sdk.window.SlideListener#slideUrlInterrupter(String, ResultCaller)} 回调，你可以在该回调中替换图片的地址。
url 统一大写，可以全局搜索替换一下

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/window/SlideListener.java
> +     * 开启后，在 Slide 资源加载时，SDK 会触发该回调，报告资源的原 URL 地址。你需要将替换后的 URL 通过 resultCaller 回调到 SDK。
```suggestion
     * 开启后，在 Slide 资源加载时，SDK 会触发该回调，报告资源的原 URL 地址。你需要将替换后的 URL 通过 `resultCaller` 回调到 SDK。
```

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/window/SlideListener.java
> +     * @since 2.16.52
是不是要改成 2.16.59

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +`WhiteSdkConfiguration` 新增 `enableSlideInterrupterAPI` 配置项。开启后，通过调用 `WhiteSdk.setSlideListener(SlideListener)` 实现 PPT 文件 URL 的拦截替换功能。
只看这里我其实不太懂拦截替换有什么用，建议搬一点 api 的描述过来，让用户看发版说明的时候就能 get 到

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +`WhiteSdkConfiguration` 新增 `whiteSlideAppParams` 配置项用于 [@netless/app-slide](https://github.com/netless-io/netless-app/tree/master/packages/app-slide) 渲染相关的显示配置。当前支持配置 `WhiteSlideAppParams.showRenderE
没看到 showRenderError 的 api 描述

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/WhiteSdkConfiguration.java
> +     * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
```suggestion
     * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 SDK 自带配置。
```

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/WhiteSdkConfiguration.java
> +    public List<String> getApiHosts() {
这个漏写了

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/WhiteSdkConfiguration.java
> +     * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
其它地方也有，可以统一搜索替换

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/WhiteSdkConfiguration.java
> +     * @param apiHosts 白板的 API 服务器域名列表 [api.example.com]。
……域名列表，例如 [api.example.com]。

应该是这个意思？

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +该版本修复了新版 Android Studio 无法预览布局的问题。
建议写一下具体版本号或版本范围

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/domain/WindowParams.java
> +        return this;
这两个 get 和 set 应该也会生成文档吧？会的话要补下描述

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/domain/WindowParams.java
> +public class WindowParams extends WhiteObject {
建议也给一句类的描述

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +使用新增的 `createSlideApp` 方法即可构建 `WindowAppParam` 对象，优化使用[新版文档转换服务](/doc/whiteboard/android/whiteboard-sdk/advanced-features/convert-files)转换 PPT 文件并插入至白板的流程。
需要点明 WindowAppParam 对象中包含了 ProjectorAttributes 和 ProjectorOptions，不然按现在的描述不太能懂这两段之间的联系

建议调下顺序，先一句话讲清楚改进点，再说怎么用。仅供参考：

该版本优化了使用[新版文档转换服务](/doc/whiteboard/android/whiteboard-sdk/advanced-features/convert-files)转换 PPT 文件并插入至白板的流程。你需要使用新增的 `createSlideApp` 方法构建 `WindowAppParam` 对象，该对象包含 `ProjectorAttributes` 和 `ProjectorOptions` 成员，xxxx

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/domain/WindowAppParam.java
> +     * @return
返回值是不是漏写了？应该是 WindowAppParam 对象

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/domain/WindowAppParam.java
> +    public static class ProjectorOptions extends Options {
好像漏写了它的描述

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/domain/WindowAppParam.java
> +    public static class ProjectorAttributes extends Attributes {
好像漏写 +1

2023-08-31 03:53 UTC, dengyaxi commented on CN/sdk/domain/WindowAppParam.java
> +    public static WindowAppParam createSlideApp(String scenePath, Scene[] scenes, String title) {
这个 createSlideApp 的重载方法需要对外咩

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +使用新增的 `createSlideApp` 方法即可构建 `WindowAppParam` 对象，优化使用[新版文档转换服务](/doc/whiteboard/android/whiteboard-sdk/advanced-features/convert-files)转换 PPT 文件并插入至白板的流程。
另外不太懂为什么要提  `manager.addApp` ，如果是和这条改进相关，需要解释一下

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +新增 `WindowParams.fullscreen`, 用于控制窗口是否全屏。
```suggestion
新增 `WindowParams.fullscreen` 属性，用于控制窗口是否全屏。
```

2023-08-31 03:53 UTC, dengyaxi commented on CN/release-notes-wb.android.mdx
> +  - `ProjectorOptions`
是不是也要写一下 WindowAppParam

2023-08-31 07:53 UTC, Nero-Hu commented on CN/release-notes-wb.android.mdx
> +该版本废弃了白板数据中心原有的英国伦敦数据中心（`Region.gb-lon`），并新增了欧洲法兰克福数据中心（`Region.eu`），服务区覆盖欧洲。如需使用该数据中心，请在升级到该版本后更新代码，并在控制台-互动白板服务配置中启用该数据中心。
是的

2023-08-31 08:04 UTC, Nero-Hu commented on CN/release-notes-wb.android.mdx
> +`WhiteSdkConfiguration` 新增 `enableSlideInterrupterAPI` 配置项。开启后，通过调用 `WhiteSdk.setSlideListener(SlideListener)` 实现 PPT 文件 URL 的拦截替换功能。
该功能可用于加密用户上传的 PPT 资源，保护用户隐私。

2023-08-31 08:05 UTC, Nero-Hu commented on CN/sdk/WhiteSdk.java
> +     * 更新当前 Slide 的音量。
换成 PPT

2023-08-31 08:15 UTC, Nero-Hu commented on CN/release-notes-wb.android.mdx
> +该版本修复了新版 Android Studio 无法预览布局的问题。
@aderan

2023-08-31 08:19 UTC, Nero-Hu commented on CN/sdk/domain/WindowParams.java
> +        return this;
已补充

2023-08-31 08:24 UTC, Nero-Hu commented on CN/release-notes-wb.android.mdx
> +使用新增的 `createSlideApp` 方法即可构建 `WindowAppParam` 对象，优化使用[新版文档转换服务](/doc/whiteboard/android/whiteboard-sdk/advanced-features/convert-files)转换 PPT 文件并插入至白板的流程。
不提 manager.addApp 了，改为“对应打开文档时传入的参数”

2023-09-11 12:21 UTC, atovpeko requested changes

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/Room.java
> +     *                  - Returns `true`, if the method call succeeds.
no comma is needed here or in the next bullet point
also, for consistency, please start the point about error message with a verb (e.g. throws an error message)

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/WhiteSdk.java
> +     * Updates the volume the PPT slide.
Updates the volume OF the PPT slide maybe?

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/WhiteSdk.java
> +     * Gets the volume the PPT slide.
Same comment - volume OF the PPT slide?

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/WhiteSdk.java
> +     * - A successful call: `volume` ranges from (0,1], indicating the volume the PPT; `error` returns `nil`.
volume OF the PPT?

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/WhiteSdk.java
> +     * PPT slides uses the `SlideListener` class to report events to App.
Slides use (plural)

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/WhiteSdkConfiguration.java
> +     * @param enableSlideInterrupterAPI Whether to enable ntercepting and replacing URLs of PPT resources:
intercepting

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/domain/WindowAppParam.java
> +     * Constructs the pamameters used to add PPT slides in whiteboard.
parameters

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/domain/WindowAppParam.java
> +     * @param prefixUrl URL begins with http or https, such as https://convertcdn.netless.link/dynamicConvert. Notice that the URL does not ends with `/`.
URL does not end

2023-09-11 12:21 UTC, atovpeko commented on EN-Compact/sdk/domain/WindowAppParam.java
> +     * @param title The title of the window. Used to display the inserted docs.
Is there a period after title? Something is wrong in these sentences

2023-10-27 02:47 UTC, merged