add 1.6.0 en api ref and release
Nero-Hu/Whiteboard-Android-doc pull request #9
Opened 2024-02-05 09:37 UTC by Nero-Hu

2024-02-06 09:15 UTC, atovpeko requested changes

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +- `preloadCount`: int. The number of WebViews to preload, defaults to `0`. The actual effect of this attribute is limited by the memory capacity. You need to adjust the settings appropriately accordi
```suggestion
- `preloadCount`: Integer. The number of WebViews to preload, defaults to `0`. The actual effect of this attribute is limited by the memory capacity. You need to adjust the settings appropriately according to the actual situation.
```

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +A class for setting the page settings for inserting documents. Includes the following attributes
```suggestion
A class for configuring the page settings for inserting documents. Includes the following attributes:
```

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +- `width`: int. The width of the inserted document in the whiteboard (px).
```suggestion
- `width`: Integer. The width of the inserted document in the whiteboard (px).
```

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +- `height`: int. The height of the inserted document in the whiteboard (px).
```suggestion
- `height`: Integer. The height of the inserted document in the whiteboard (px).
```

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +- `logger`: The logger instance. If you need to customize the logger, you need to pass in an implementation class of the `Logger` interface, see [`Logger`](#logger); passing in `null` will use the sy
I would change "will use" to "will result in using" for better grammar

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +Record a info log.
```suggestion
Record an info log. 
```

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-API Reference.md
> +Record a error 级别日志.
1. a --> an
2. The Chinese part still needs to be translated, I assume?

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-Release Notes.md
> +Adds the `FastLogger` class to provide a flexible whiteboard runtime log recording tool, which can easily record `debug`, `info`, `warn`, and `error` four different levels of log information. You can
```suggestion
Adds the `FastLogger` class to provide a flexible whiteboard runtime log recording tool, which can easily record four different levels of log information: `debug`, `info`, `warn`, and `error` . You can call the `setLogger` method to customize the logger to adapt to different logging needs, or you can use the system `Log` class to log.
```

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-Release Notes.md
> +- The full room state callback roomState after joining the room is disabled. Clients need to call `Room.getRoomState()` to get the full `RoomState`.
The full room state callback roomState after joining the room is disabled - > this sentence is slightly awkward, can it be rephrased for readability?

2024-02-06 09:15 UTC, atovpeko commented on Fastboard/EN-Release Notes.md
> +**Depreacated**
```suggestion
**Deprecated**
```

2024-02-07 09:13 UTC, Nero-Hu commented on Fastboard/EN-Release Notes.md
> +- The full room state callback roomState after joining the room is disabled. Clients need to call `Room.getRoomState()` to get the full `RoomState`.
Please check if this version is better.
The room state callback, `roomState`, which is triggered after joining a whiteboard room, is disabled. You need to call `Room.getRoomState()` to get the complete `RoomState`.

2024-04-09 03:11 UTC, merged